layer_ids:
  layer_1: FC BF D8 7B 00
  layer_2: A2 85 D9 DA 0C
  layer_3: A1 B3 D9 B2 07
  layer_4: F6 A5 CA FC 01

randomize:
  seed: 12345
  replace_all: false
  sources:
    - layer_2
    - layer_3
    - layer_4
  targets:
    layer_2: 1
    layer_3: 1
    layer_4: 1
